repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: venv/bin/pytest tests --cov=app --cov-report=term --cov-report=html:coverage-report
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
